In [8]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import KFold
import pandas as pd
from helper import *
pd.options.display.max_columns = None

## Import DataSet

In [90]:
sumdata_url = "https://www.dropbox.com/sh/euppz607r6gsen2/AABABUTdx7YqCeBquA1Ky7z8a/The%20SUM%20dataset?dl=1#"
housing_price_url = "https://www.dropbox.com/sh/euppz607r6gsen2/AAAVLZzU4E7ro0BiRzPG3pP8a/House%20Prices?dl=1"
census_data_url = "https://www.dropbox.com/sh/euppz607r6gsen2/AADfweTUjMlkayMQ6JvKUOGia/Census-Income%20(KDD)%20Data%20Set?dl=0"
all_urls = [sumdata_url, housing_price_url, census_data_url]

In [91]:
get_data(all_urls) # retrieves the data if there is no data folder

In [11]:
sumdata_noise_path = "data/with noise/The SUM dataset, with noise.csv"
sumdata_path = "data/without noise/The SUM dataset, without noise.csv"
housing_price_path = "data/housing dataset.csv" # has more than 30 features
census_path = "data/housing dataset.csv"
titanic_path = "data/"
# need one more
# what a brilliant idea to name files with space

## Load datasets sum_noise

In [13]:
sumdata_noise = pd.read_csv(sumdata_noise_path, delimiter=";")
sumdata_noise

Instance  Feature 1  Feature 2  Feature 3  Feature 4  \
0              1      66957      74432      96087     103120   
1              2      96030      86875     108299     148025   
2              3      26212      23398      27668      39678   
3              4      28363      33381      42447      35270   
4              5      38960      50255      79879      91885   
5              6      34616      45307      50710      58657   
6              7      12888      20126      22753      23219   
7              8      30922      38291      43157      53434   
8              9      33869      47235      53800      69464   
9             10      28247      24863      41941      38753   
10            11      11533      15105      15618      20434   
11            12     100336     136636     123603     190534   
12            13      14904      21058      22569      28412   
13            14      37161      40892      53308      51163   
14            15      37394      53690      61280      73309   
15            16      31363      32102      54582      51201   
16            17      38577      49221      60327      72657   
17            18      61255      79958      85804     105528   
18            19      69378     102553     122961     121382   
19            20      92869      96203     124016     165965   
20            21      74146      65371      79886     104850   
21            22      17373      22042      25303      34805   
22            23      45353      69765      69150      78718   
23            24      85805     102966     130912     168282   
24            25      24672      28461      38071      42469   
25            26      25440      30591      40500      43105   
26            27      66846      86768      93007     130986   
27            28      75965     107280     134577     125135   
28            29      51466      75398      98385     117070   
29            30       7117       8618      12699      16359   
...          ...        ...        ...        ...        ...   
968105    968106      51398      71774      69898      86394   
968106    968107       8615       8377      14140      12690   
968107    968108      70454     110653     104621     125953   
968108    968109     110177     117559     135701     176211   
968109    968110      41150      62812      61559      69970   
968110    968111       5432       5150       7967       7358   
968111    968112      60792      82682      97070     108411   
968112    968113      27706      24287      32547      45357   
968113    968114      32738      43185      49026      68009   
968114    968115      32860      48010      46921      53573   
968115    968116      81669      98688     153968     161048   
968116    968117      39588      38235      46932      49788   
968117    968118      59206      94438      99195     130376   
968118    968119      87340     107978     148458     135501   
968119    968120      12519      19407      23519      26361   
968120    968121      85601     111403     144856     175032   
968121    968122      98042      97688     105122     139143   
968122    968123      18039      16090      22828      24484   
968123    968124     104486      99475     141475     167374   
968124    968125      12901      11183      15072      16344   
968125    968126      28225      31030      42327      51931   
968126    968127      70631      81905     120290     128652   
968127    968128      58432      85549      81839     110640   
968128    968129      11098      12826      12886      17468   
968129    968130      11194      12923      18877      21917   
968130    968131      31192      37027      48520      69843   
968131    968132     101113      98421     134466     161029   
968132    968133      50930      72366     103989     105850   
968133    968134      71701      71511     113123     121883   
968134    968135      20982      22541      24868      35491   

        Feature 5 (meaningless)  Featur

## Preprocess sum_noise dataset

- Remove 'Instance' as it simply represents the row number
- Extract 'Nosiy Target' as regression target
- Extract 'Nosiy Class' as classification target
- Extract rest columns as explananatory variables
- Apply Feature Scaling to the dataset 

- Ensure all dataframe has been converted to numpy array


In [14]:
# Remove 'Instance' as it simply represents the row number
sumdata_noise.drop('Instance', axis = 1)

# Use 'Nosiy Target' as regression target
sumdata_noise_reg_Y = sumdata_noise['Noisy Target'].values.reshape(-1, 1)

# Use 'Nosiy Target Class' as regression target
sumdata_noise_classif_Y = sumdata_noise['Noisy Target Class']

# Use rest columns as explananatory variables
sumdata_noise_X = sumdata_noise.iloc[:, 0:-2]

# Apply Feature Scaling to the dataset 
from sklearn.preprocessing import StandardScaler
scX = StandardScaler()
scY = StandardScaler()
sumdata_noise_X = scX.fit_transform(sumdata_noise_X)
sumdata_noise_reg_Y = scY.fit_transform(sumdata_noise_reg_Y)

sumdata_noise_X

/Users/kiyim/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:444: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


array([[-1.73204902,  0.57148372,  0.40463575, ...,  0.01029815,
         0.01473561,  0.29953474],
       [-1.73204544,  1.55295829,  0.75447754, ...,  0.8441455 ,
         1.48881339,  1.86218921],
       [-1.73204186, -0.80402556, -1.03021326, ..., -1.04344437,
        -1.04000593, -0.93382741],
       ..., 
       [ 1.73204186,  0.03042869,  0.34654902, ...,  0.76615191,
         0.79476291,  0.37581042],
       [ 1.73204544,  0.73163628,  0.32251022, ...,  0.86467558,
         1.10936719,  0.36614112],
       [ 1.73204902, -0.98058498, -1.05430829, ..., -1.14767765,
        -1.17865895, -1.17127118]])

## Load datasets sumdata

In [15]:
sumdata = pd.read_csv(sumdata_path, delimiter=";")
sumdata.head(n=1)

Instance  Feature 1  Feature 2  Feature 3  Feature 4  \
0         1      57326      68791      82549      99059   

   Feature 5 (meaningless)  Feature 6  Feature 7  Feature 8  Feature 9  \
0                    72624     142645     171174     205409     246491   

   Feature 10   Target       Target Class  
0      295789  1073444  Very Large Number

## Preprocess sumdata dataset

- Remove 'Instance' as it simply represents the row number
- Extract 'Nosiy Target' as regression target
- Extract 'Nosiy Class' as classification target
- Extract rest of the columns as explananatory variables
- Apply Feature Scaling to the dataset 

- Ensure all dataframe has been converted to numpy array


In [16]:
# Remove 'Instance' as it simply represents the row number
sumdata.drop('Instance', axis = 1)

# Use 'Nosiy Target' as regression target
sumdata_reg_Y = sumdata['Target'].reshape(-1, 1)

# Use 'Nosiy Target Class' as classification target
sumdata_classif_Y = sumdata['Target Class']

# Use rest columns as explananatory variables
sumdata_X = sumdata.iloc[:, 0:-2]

# Apply Feature Scaling to the dataset 
from sklearn.preprocessing import StandardScaler
scX = StandardScaler()
scY = StandardScaler()
sumdata_X = scX.fit_transform(sumdata_X)
sumdata_reg_Y = scY.fit_transform(sumdata_reg_Y)

sumdata_X

/Users/kiyim/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:5: FutureWarning: reshape is deprecated and will raise in a subsequent release. Please use .values.reshape(...) instead
  """
/Users/kiyim/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:444: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


array([[-1.73204902,  0.25276029,  0.25275451, ...,  0.25275618,
         0.25275779,  0.25275645],
       [-1.73204544,  1.31055785,  1.31056363, ...,  1.31055123,
         1.31055284,  1.31055016],
       [-1.73204186, -0.91146488, -0.91147066, ..., -0.91146134,
        -0.91146456, -0.91146591],
       ..., 
       [ 1.73204186,  0.46131959,  0.46131382, ...,  0.46131792,
         0.46131792,  0.46131657],
       [ 1.73204544,  0.79373264,  0.79372687, ...,  0.79372498,
         0.79372497,  0.79372229],
       [ 1.73204902, -1.09338264, -1.09338265, ..., -1.09338604,
        -1.09338765, -1.09339034]])

## Load housing price dataset

In [74]:
housing_price = pd.read_csv(housing_price_path)
housing_price = housing_price#
housing_price.head(n=5)

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg   
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   
3   4          70       RL         60.0     9550   Pave   NaN      IR1   
4   5          60       RL         84.0    14260   Pave   NaN      IR1   

  LandContour Utilities LotConfig LandSlope Neighborhood Condition1  \
0         Lvl    AllPub    Inside       Gtl      CollgCr       Norm   
1         Lvl    AllPub       FR2       Gtl      Veenker      Feedr   
2         Lvl    AllPub    Inside       Gtl      CollgCr       Norm   
3         Lvl    AllPub    Corner       Gtl      Crawfor       Norm   
4         Lvl    AllPub       FR2       Gtl      NoRidge       Norm   

  Condition2 BldgType HouseStyle  OverallQual  OverallCond  YearBuilt  \
0       Norm     1Fam     2Story            7            5       2003   
1       Norm     1Fam     1Story            6            8       1976   
2       Norm     1Fam     2Story            7            5       2001   
3       Norm     1Fam     2Story            7            5       1915   
4       Norm     1Fam     2Story            8            5       2000   

   YearRemodAdd RoofStyle RoofMatl Exterior1st Exterior2nd MasVnrType  \
0          2003     Gable  CompShg     VinylSd     VinylSd    BrkFace   
1          1976     Gable  CompShg     MetalSd     MetalSd       None   
2          2002     Gable  CompShg     VinylSd     VinylSd    BrkFace   
3          1970     Gable  CompShg     Wd Sdng     Wd Shng       None   
4          2000     Gable  CompShg     VinylSd     VinylSd    BrkFace   

   MasVnrArea ExterQual ExterCond Foundation BsmtQual BsmtCond BsmtExposure  \
0       196.0        Gd        TA      PConc       Gd       TA           No   
1         0.0        TA        TA     CBlock       Gd       TA           Gd   
2       162.0        Gd        TA      PConc       Gd       TA           Mn   
3         0.0        TA        TA     BrkTil       TA       Gd           No   
4       350.0        Gd        TA      PConc       Gd       TA           Av   

  BsmtFinType1  BsmtFinSF1 BsmtFinType2  BsmtFinSF2  BsmtUnfSF  TotalBsmtSF  \
0          GLQ         706          Unf           0        150          856   
1          ALQ         978          Unf           0        284         1262   
2          GLQ         486          Unf           0        434          920   
3          ALQ         216          Unf           0        540          756   
4          GLQ         655          Unf           0        490         1145   

  Heating HeatingQC CentralAir Electrical  1stFlrSF  2ndFlrSF  LowQualFinSF  \
0    GasA        Ex          Y      SBrkr       856       854             0   
1    GasA        Ex          Y      SBrkr      1262         0             0   
2    GasA        Ex          Y      SBrkr       920       866             0   
3    GasA        Gd          Y      SBrkr       961       756             0   
4    GasA        Ex          Y      SBrkr      1145      1053             0   

   GrLivArea  BsmtFullBath  BsmtHalfBath  FullBath  HalfBath  BedroomAbvGr  \
0       1710             1             0         2         1             3   
1       1262             0             1         2         0             3   
2       1786             1             0         2         1             3   
3       1717             1             0         1         0             3   
4       2198             1             0         2         1             4   

   KitchenAbvGr KitchenQual  TotRmsAbvGrd Functional  Fireplaces FireplaceQu  \
0             1          Gd             8        Typ           0         NaN   
1             1          TA             6        Typ           1          TA   
2             1          Gd             6        Typ           1          TA   
3             1          Gd            

## Preprocess housing price dataset

- Remove 'Id' as it simply represents the row number
- Use 'SalePrice' as regression target
- Use 'SaleCondition' as classification target
- For explananatory variables, use all the numerical variable and use the following categorical variables
    - Neighborhood, as the career of the neighbour impacts on factors such as the consuming power of the area 
    - HouseStyle, well-designed house is more expensive
- Apply Feature Scaling to the dataset 

- Ensure all dataframe has been converted to numpy array


In [81]:
# Remove 'Instance' as it simply represents the row number
housing_price.drop('Id', axis = 1)

# Use 'Nosiy Target' as regression target
housing_price_reg_Y = [housing_price['SalePrice']]

# Use 'Nosiy Target Class' as classification target
housing_price_classif_Y = housing_price['SaleCondition']

# Get all the numeric variables
housing_price_X = housing_price.iloc[:, 0:-2]._get_numeric_data()

# Get the two chosen categorical variables and add them to
housing_price_X = pd.concat([housing_price_X, pd.get_dummies(housing_price['Neighborhood']).iloc[:, :-1]], axis=1)
housing_price_X = pd.concat([housing_price_X, pd.get_dummies(housing_price['HouseStyle']).iloc[:, :-1]], axis=1)
housing_price_X = housing_price_X.dropna()
housing_price_X

# Apply Feature Scaling to the numeric variables and regression target 
scX = StandardScaler()
scY = StandardScaler()
housing_price_X = scX.fit_transform(housing_price_X)
housing_price_reg_Y = scY.fit_transform(housing_price_reg_Y)
housing_price_classif_Y = housing_price_classif_Y.values



# Fits Algorithms to datasets

In [102]:
data_chunks = [100, 500, 1000, 5000, 10000, 50000, 100000, 500000,
1000000, 5000000, 10000000, 50000000, 100000000]

In [123]:
def model( X, y, dataset_name, algorithm=LinearRegression): 
    
    algo_name = algorithm.__name__
    for chunk in data_chunks:
        
        if chunk > X.shape[0]: # if chunk is greater than the no. of examples
            break

        X = X[:, 0:chunk]
        y = y[:, 0:chunk]

        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
        lm = algorithm()
        model = lm.fit(X_train, y_train)
        
        predictions = model.predict(X_test)
        # Validate the model
#         kFoldModel()
        #print(predictions)
        
        error = mean_squared_error(y_test, predictions)**0.5  # RMSE https://www.kaggle.com/wiki/RootMeanSquaredError
        print ("Data set: {} Algorithm: {}  Chunk Size: {} Error: {}".format(dataset_name,
                                                                          algo_name,
                                                                          chunk,
                                                                           error
                                                                         ))
              
         
    

In [124]:
def kFoldModel (X, y, data_set, kfolds, algorithm=LinearRegression):
    
    algo_name = algorithm.__name__
    
    kf = KFold(n_splits=kfolds)
    
    for train, test in kf.split(data_set):
        print("%s %s" % (train, test))

## Fits Regression Algorithms to datasets

    - Linear Regression
    - Random Forest Regression
    

In [125]:
from sklearn.ensemble import RandomForestRegressor

model(sumdata_noise_X, sumdata_noise_reg_Y,"The Sum Dataset(without noise)", LinearRegression )
sumdata_noise_X.shape
# model(sumdata_X, sumdata_reg_Y,"The Sum Dataset(without noise)", LinearRegression )
# model(housing_price_X, housing_price_reg_Y,"The Sum Dataset(without noise)", LinearRegression )

# model(sumdata_noise_X, sumdata_noise_reg_Y,"The Sum Dataset(with noise)", RandomForestRegressor )
# model(sumdata_X, sumdata_reg_Y, "The Sum Dataset(with noise)", RandomForestRegressor )
# model(housing_price_X, housing_price_reg_Y, "The Sum Dataset(with noise)", RandomForestRegressor )

Data set: The Sum Dataset(without noise) Algorithm: LinearRegression  Chunk Size: 100 Error: 0.11468765043817408
Data set: The Sum Dataset(without noise) Algorithm: LinearRegression  Chunk Size: 500 Error: 0.11481809958377741
Data set: The Sum Dataset(without noise) Algorithm: LinearRegression  Chunk Size: 1000 Error: 0.11493496516094923
Data set: The Sum Dataset(without noise) Algorithm: LinearRegression  Chunk Size: 5000 Error: 0.11464165445529044
Data set: The Sum Dataset(without noise) Algorithm: LinearRegression  Chunk Size: 10000 Error: 0.11481578692945582
Data set: The Sum Dataset(without noise) Algorithm: LinearRegression  Chunk Size: 50000 Error: 0.11433754847630337
Data set: The Sum Dataset(without noise) Algorithm: LinearRegression  Chunk Size: 100000 Error: 0.1147897849936184
Data set: The Sum Dataset(without noise) Algorithm: LinearRegression  Chunk Size: 500000 Error: 0.115041819870308


(968135, 11)

In [ ]:
model(sumdata_X, sumdata_y,"Sum without noise", LinearRegression )

# DID do cross validation

In [15]:
kFoldModel(sumdata_noise_X, sumdata_noise_reg_Y, "Noisy Sum", 2, LinearRegression )

[5 6 7 8] [0 1 2 3 4]
[0 1 2 3 4] [5 6 7 8]
